#Docker file for VueJS using NGINX
# build stage
FROM node:20 as build-stage

WORKDIR /app

COPY /frontend/package*.json ./
#COPY /frontend/yarn.lock ./

RUN yarn install

COPY ./frontend .

RUN yarn run build



FROM nginx:stable-alpine as production-stage

COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=build-stage /app/dist/spa /app

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]